### ISSUE TITLE
Bot no longer recognizes mods/broadcaster

### ISSUE THREAD

**Issue by D-Skye** [pejter/twitch-queue-bot#33]
The bot currently recognizes user commands, but no longer recognizes mod commands, even from the streamer. May be some sort of Twitch chat API update?

(this is the behavior from roborollbackian, in sajam's channel)

**Comment by pejter** [comment]
Indeed there was a twitch API change which I did not see the announcement for. The change is that you can no longer get the list of moderators from the chat commands, so i'll need to update it.

**Comment by pejter** [comment]
The newest update should fix it for the broadcaster. It was an oversight where I forgot to add them to the initial list of mods, but  did add them once the mod list was updated.
However fixing the mod list as a whole is a more major change because I have to not interact with the twitch API, which requires me to make a developer app and for the broadcaster to authorise it to access the mod list. So it will take some more time.

**Comment by D-Skye** [comment]
Thanks for looking into it. Having it work with the broadcaster is great for now, we can work with that. Appreciate the quick response!

**Comment by pejter** [comment]
Fixed in deb26d17f194d1faa2669b78d76a891988734d97
